set langmenu=en_US.UTF-8
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
language messages en_US.utf-8

set nocompatible
syntax on

set smartindent

set shiftwidth=2
set tabstop=2
set expandtab
set smarttab

set scrolloff=999

set encoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,euc-jp,euc-kr,latin1

colorscheme xoria256 

set laststatus=2
set statusline=
set statusline+=%-3.3n\
set statusline+=%f\
set statusline+=%h%m%r%w
set statusline+=\[%{strlen(&ft)?&ft:'none'}]
set statusline+=%=
set statusline+=0x%-8B
set statusline+=%-14(%l,%c%V%)
set statusline+=%<%P

set ruler
set number

set showcmd

set incsearch
set ignorecase
set hls

set wildmenu
set showmode
set visualbell

set lines=35 columns=99

set guioptions-=m
set guioptions-=T

set guifont=consolas:h14


" allow the . to execute once for each line of a visual selection
vnoremap . :normal .<CR>
